/* eslint-env node */
/**
 * Finds the newest `*resume*.pdf` (case-insensitive) inside /public and:
 *   1. writes its public URL to src/data/resumeFile.ts (imported by the Hero), and
 *   2. keeps the resume entry in public/sitemap.xml pointing at the same file.
 *
 * This lets you drop in a versioned resume (e.g. "Bibin Alias Resume IN 6.1.6.pdf")
 * without editing any code — the site picks it up automatically on the next build.
 *
 * Runs automatically from next.config.js on `next dev`, `next build`, and `next export`.
 */
const fs = require('fs');
const path = require('path');

const SITE_URL = 'https://bibinalias.github.io';
const ROOT = path.join(__dirname, '..');
const PUBLIC_DIR = path.join(ROOT, 'public');
const OUT_TS = path.join(ROOT, 'src', 'data', 'resumeFile.ts');
const SITEMAP = path.join(PUBLIC_DIR, 'sitemap.xml');

function findResumePdf() {
  let files;
  try {
    files = fs.readdirSync(PUBLIC_DIR);
  } catch {
    return null;
  }

  const matches = files
    .filter(f => /resume/i.test(f) && f.toLowerCase().endsWith('.pdf'))
    .map(f => ({name: f, mtime: fs.statSync(path.join(PUBLIC_DIR, f)).mtimeMs}))
    // newest file wins, so the latest exported resume is always used
    .sort((a, b) => b.mtime - a.mtime);

  return matches.length ? matches[0].name : null;
}

function writeResumeModule(url) {
  const content =
    '// AUTO-GENERATED by scripts/resolve-resume.js - do not edit by hand.\n' +
    '// Points to the newest `*resume*.pdf` found in /public.\n' +
    `export const resumeFileUrl = '${url}';\n`;
  fs.writeFileSync(OUT_TS, content, 'utf8');
}

function updateSitemap(url) {
  if (!url) return;
  let xml;
  try {
    xml = fs.readFileSync(SITEMAP, 'utf8');
  } catch {
    return;
  }
  const fullUrl = `${SITE_URL}${url}`;
  // replace whatever .pdf loc currently exists with the resolved one
  const updated = xml.replace(/<loc>\s*https:\/\/[^<]*\.pdf\s*<\/loc>/i, `<loc>${fullUrl}</loc>`);
  if (updated !== xml) {
    fs.writeFileSync(SITEMAP, updated, 'utf8');
  }
}

function resolveResume() {
  const chosen = findResumePdf();
  const url = chosen ? '/' + encodeURI(chosen) : '';
  writeResumeModule(url);
  updateSitemap(url);
  // eslint-disable-next-line no-console
  console.log(chosen ? `[resolve-resume] using: ${url}` : '[resolve-resume] no *resume*.pdf found in /public');
  return url;
}

module.exports = resolveResume;

if (require.main === module) {
  resolveResume();
}
