// AUTO-GENERATED by scripts/resolve-resume.js - do not edit by hand.
// Points to the newest `*resume*.pdf` found in /public.
export const resumeFileUrl = '/Bibin%20Alias%20Resume%20IN%206.1.6.pdf';
